# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "itf_base_box.box"
  # config.vm.provision :shell, path: "bootstrap.sh" #Ryan silly
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  #config.vm.synced_folder "VagrantData", "/vagrant_data"

  # SSH Data
  config.ssh.password="vagrant"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
   config.vm.provider "virtualbox" do |vb|
  #  Display the VirtualBox GUI when booting the machine
     vb.gui = false

  #  Customize the amount of memory on the VM:
     vb.memory = "4096"
   end

   config.vm.provision "update-ITF", type: "shell", inline: <<-SHELL
    #rm -rf Integration-Testing-Framework
    #git clone http://github.com/sillsdev/Integration-Testing-Framework
    # Copy ITF site-packages to the default SikuliRepo/Lib folder
    #mkdir ~/.Sikulix/Lib -p
    cd Integration-Testing-Framework
    git pull
    cp -r ~/Integration-Testing-Framework/site-packages ~/.Sikulix/Lib
    cd ..
   SHELL

   config.vm.provision "bootstrap", type: "shell", inline: <<-SHELL
	sudo echo deb http://packages.sil.org/ubuntu trusty main >> /etc/apt/sources.list
	sudo echo deb http://packages.sil.org/ubuntu trusty-experimental main >> /etc/apt/sources.list
	wget http://packages.sil.org/sil.gpg -O- | sudo apt-key add -
	sudo apt-get update
	sudo apt-get autoremove
	sudo apt-get autoclean

	rm -rf FwIntegrationTests
	git clone http://github.com/sillsdev/FwIntegrationTests
	### Set permissions and ownership on /home/vagrant
	#sudo find . -name '.*' -prune -o -exec chmod u=rwx,g=rx,o=r {} +
	#sudo find . -name '.*' -prune -o -exec chown -R vagrant . {} +
	sudo chown -R vagrant /home/vagrant

	cp -r ~/FwIntegrationTests/site-packages ~/.Sikulix/Lib
	#### Vagrant User Configurations
	####
	sudo su vagrant << EOF
export DISPLAY=:0.0
echo "vagrant" > ~/.Sikulix/Lib/site-packages/logFolder.txt

#\/not tested with vagrant\/
# Windows #
#echo "" > (($Env:APPDATA)+"\Sikulix\Lib\site-packages\logFolder.txt")
# Mac     #
#echo "vagrant" > ~/Library/Application Support/Sikulix/Lib/site-packages/logFolder.txt

### Install French keyboard (and keep English keyboard)
gsettings set org.gnome.desktop.input-sources sources  "[('xkb', 'us'), ('xkb', 'fr')]"

### Disable the screen blackout and lock:
gsettings set org.gnome.desktop.session idle-delay 0
gsettings set org.gnome.desktop.screensaver ubuntu-lock-on-suspend false
gsettings set org.gnome.desktop.screensaver lock-enabled false

### Could be done in autostart script - it exists, but needs to finish before sikuli starts
sudo apt-get -y install libswing-layout-java tesseract-ocr tesseract-ocr-eng gnome-panel
rm -r /tmp/sikuli
mkdir -p /tmp/sikuli
ln -s /usr/share/tesseract-ocr/tessdata/ /tmp/sikuli

EOF
# The EOF is not indented because whitespace (a tab) causes an error.
	####
	####

	### Installation of FLEX, the first line assumes "More" is not needed, the second assumes "More" is used.
	sudo apt-get update
	sudo echo "debconf debconf/frontend select Readline" | sudo debconf-set-selections
	sudo expect FwIntegrationTests/scripts/fwapp_install_nomore.exp

	### For manual install, use [more] exp script
	#sudo expect FwIntegrationTests/scripts/fwapp_install.exp 2>> /vagrant/error_log

	### Language libraries
	sudo apt-get -y install fieldworks-l10n-*

   SHELL

end
